/** Generated by scripts/sync-contracts.py — do not edit by hand. */

export const ADMIN_WEB_HOSTNAME = "admin.lx-software.com" as const;

export const PARSE_TIMEOUTS = {
  lambdaTimeoutSeconds: 300,
  openRouterTimeoutSeconds: 210,
  parseJobStaleSeconds: 330,
  parseJobStuckSeconds: 420,
  parseJobTtlSeconds: 604800,
  parsePollDeadlineMs: 480000,
} as const;
