/** Generated by scripts/sync-contracts.py — do not edit by hand. */

export const SUPPORTED_CURRENCIES = ["GBP", "HKD", "USD", "EUR", "CNY", "SGD", "AED"] as const;
export type CurrencyCode = (typeof SUPPORTED_CURRENCIES)[number];
export const GLOBAL_DEFAULT_CURRENCY: CurrencyCode = "HKD";

export const FINANCE_HOUSE_KEYS = ["hillmarton", "morrison"] as const;
export type HouseKey = (typeof FINANCE_HOUSE_KEYS)[number];

export const INCOME_CATEGORIES = ["Salary", "Rent"] as const;
export const EXPENSE_CATEGORIES = ["Utility", "Saving", "Investment", "Rent", "Mortgage", "Insurance", "Retirement", "Tax", "Amenities", "Helper", "Education"] as const;
export const INVESTMENT_CATEGORIES = ["Real Estate", "Fixed Term Deposit", "ETF", "Crypto"] as const;
export const ASSET_TYPES = ["Fixed", "Liquid"] as const;
export const FINANCE_ACCOUNT_TYPES = ["Bank Account", "Credit Card", "Debit Card"] as const;

export const PARSE_POLL_DEADLINE_MS = 480000;
export const PARSE_POLL_INITIAL_WAIT_MS = 1000;
export const PARSE_POLL_BACKOFF_CAP_MS = 5000;

export const ADMIN_WEB_HOSTNAME = "admin.lx-software.com";
