"""Generated by scripts/sync-contracts.py — do not edit by hand."""

from __future__ import annotations

from pathlib import Path
import json

_CONTRACTS_DIR = Path(__file__).resolve().parent / "contracts"

def _load(name: str) -> dict:
    with (_CONTRACTS_DIR / name).open(encoding="utf-8") as f:
        return json.load(f)

FINANCE_CONTRACT = _load("finance.json")
PARSE_TIMEOUTS_CONTRACT = _load("parse-timeouts.json")
ADMIN_DOMAINS_CONTRACT = _load("admin-domains.json")
EXECUTIVE_BOARD_CONTRACT = _load("executive-board.json")
BOARD_TIMEOUTS_CONTRACT = _load("board-timeouts.json")

FINANCE_HOUSE_KEYS = frozenset(FINANCE_CONTRACT["houses"])
FINANCE_STATEMENT_BOOK_KEYS = frozenset(FINANCE_CONTRACT["statementBooks"])
FINANCE_STATEMENT_OWNER_KEYS = FINANCE_HOUSE_KEYS | FINANCE_STATEMENT_BOOK_KEYS
FINANCE_LINE_TYPES = frozenset(FINANCE_CONTRACT["lineTypes"])
SUPPORTED_FINANCE_CURRENCIES = frozenset(FINANCE_CONTRACT["currencies"])
DEFAULT_FINANCE_CURRENCY = FINANCE_CONTRACT["defaultCurrency"]
INCOME_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT["incomeCategories"])
EXPENSE_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT["expenseCategories"])
INVESTMENT_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT["investmentCategories"])
ASSET_TYPES = frozenset(FINANCE_CONTRACT["assetTypes"])
FINANCE_ACCOUNT_TYPES = frozenset(FINANCE_CONTRACT["accountTypes"])
FINANCE_LIABILITY_TYPES = frozenset(FINANCE_CONTRACT["liabilityTypes"])
LEDGER_RECORD_AMOUNT_PERIODS = frozenset(FINANCE_CONTRACT["ledgerAmountPeriods"])

_LIMITS = FINANCE_CONTRACT["limits"]
MAX_FINANCE_LINES = _LIMITS["maxFinanceLines"]
MAX_FINANCE_DESCRIPTION = _LIMITS["maxFinanceDescription"]
MAX_SOURCE_ASSET_KEYS_PER_LINE = _LIMITS["maxSourceAssetKeysPerLine"]
MAX_SOURCE_ASSET_KEY_LEN = _LIMITS["maxSourceAssetKeyLen"]
MAX_INVESTMENT_PROVIDER_LEN = _LIMITS["maxInvestmentProviderLen"]
MAX_INVESTMENT_TICKER_LEN = _LIMITS["maxInvestmentTickerLen"]
MAX_INVESTMENT_CRYPTO_CURRENCY_LEN = _LIMITS["maxInvestmentCryptoCurrencyLen"]
MAX_LEDGER_RECORDS = _LIMITS["maxLedgerRecords"]
MAX_PENSION_DESCRIPTION_LEN = _LIMITS["maxPensionDescriptionLen"]
MAX_ACCOUNT_DESCRIPTION_LEN = _LIMITS["maxAccountDescriptionLen"]

DEFAULT_EXPENSE_INCOME_ALLOCATION_PERCENTAGES: dict[str, float] = {
    "taxOnIncomePercent": FINANCE_CONTRACT["defaultExpenseIncomeAllocationPercents"]["taxOnIncomePercent"],
    "investmentOnIncomePercent": FINANCE_CONTRACT["defaultExpenseIncomeAllocationPercents"]["investmentOnIncomePercent"],
    "savingOnIncomePercent": FINANCE_CONTRACT["defaultExpenseIncomeAllocationPercents"]["savingOnIncomePercent"],
}

OPENROUTER_TIMEOUT_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT["openRouterTimeoutSeconds"])
PARSE_JOB_STALE_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT["parseJobStaleSeconds"])
PARSE_JOB_STUCK_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT["parseJobStuckSeconds"])
PARSE_JOB_TTL_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT["parseJobTtlSeconds"])
ADMIN_WEB_HOSTNAME = ADMIN_DOMAINS_CONTRACT["adminWebHostname"]

BOARD_KEY = EXECUTIVE_BOARD_CONTRACT["boardKey"]
BOARD_CHAIR_DEFAULT = EXECUTIVE_BOARD_CONTRACT["chairDefault"]
BOARD_PERSONAS: list[dict] = list(EXECUTIVE_BOARD_CONTRACT["personas"])
BOARD_PERSONA_IDS = tuple(p["id"] for p in BOARD_PERSONAS)
BOARD_MEETING_MODES = frozenset(EXECUTIVE_BOARD_CONTRACT["meetingModes"])
BOARD_ACTION_PRIORITIES = tuple(EXECUTIVE_BOARD_CONTRACT["actionPriorities"])
BOARD_ACTION_STATUSES = frozenset(EXECUTIVE_BOARD_CONTRACT["actionStatuses"])
BOARD_ACTION_EFFORTS = frozenset(EXECUTIVE_BOARD_CONTRACT["actionEfforts"])
_BOARD_LIMITS = EXECUTIVE_BOARD_CONTRACT["limits"]
BOARD_MAX_CHARTER_FIELD_LEN = _BOARD_LIMITS["maxCharterFieldLen"]
BOARD_MAX_DISPLAY_NAME_LEN = _BOARD_LIMITS["maxDisplayNameLen"]
BOARD_MAX_BRIEF_LEN = _BOARD_LIMITS["maxBriefLen"]
BOARD_MAX_UPDATE_LEN = _BOARD_LIMITS["maxUpdateLen"]
BOARD_MAX_CHAT_MESSAGE_LEN = _BOARD_LIMITS["maxChatMessageLen"]
BOARD_MAX_TOPIC_LEN = _BOARD_LIMITS["maxTopicLen"]
BOARD_MAX_ACTION_NOTE_LEN = _BOARD_LIMITS["maxActionNoteLen"]
BOARD_CHAT_HISTORY_TURNS = _BOARD_LIMITS["chatHistoryTurns"]
BOARD_MAX_DAILY_BUDGET_USD = _BOARD_LIMITS["maxDailyBudgetUsd"]

BOARD_CHAT_OPENROUTER_TIMEOUT_SECONDS = int(BOARD_TIMEOUTS_CONTRACT["chatOpenRouterTimeoutSeconds"])
BOARD_PHASE_OPENROUTER_TIMEOUT_SECONDS = int(BOARD_TIMEOUTS_CONTRACT["phaseOpenRouterTimeoutSeconds"])
BOARD_MAX_PARALLEL_PERSONA_CALLS = int(BOARD_TIMEOUTS_CONTRACT["maxParallelPersonaCalls"])
BOARD_CHAT_JOB_TTL_SECONDS = int(BOARD_TIMEOUTS_CONTRACT["chatJobTtlSeconds"])
BOARD_CHAT_JOB_STUCK_SECONDS = int(BOARD_TIMEOUTS_CONTRACT["chatJobStuckSeconds"])
BOARD_MEETING_STUCK_SECONDS = int(BOARD_TIMEOUTS_CONTRACT["meetingStuckSeconds"])
BOARD_REPO_SNAPSHOT_STALE_SECONDS = int(BOARD_TIMEOUTS_CONTRACT["repoSnapshotStaleSeconds"])
BOARD_DEFAULT_DAILY_BUDGET_USD = float(BOARD_TIMEOUTS_CONTRACT["defaultDailyBudgetUsd"])
