"""Generated by scripts/sync-contracts.py — do not edit by hand."""

from __future__ import annotations

from pathlib import Path
import json

_CONTRACTS_DIR = Path(__file__).resolve().parent / "contracts"

def _load(name: str) -> dict:
    with (_CONTRACTS_DIR / name).open(encoding="utf-8") as f:
        return json.load(f)

FINANCE_CONTRACT = _load("finance.json")
PARSE_TIMEOUTS_CONTRACT = _load("parse-timeouts.json")
ADMIN_DOMAINS_CONTRACT = _load("admin-domains.json")

FINANCE_HOUSE_KEYS = frozenset(FINANCE_CONTRACT["houses"])
FINANCE_LINE_TYPES = frozenset(FINANCE_CONTRACT["lineTypes"])
SUPPORTED_FINANCE_CURRENCIES = frozenset(FINANCE_CONTRACT["currencies"])
DEFAULT_FINANCE_CURRENCY = FINANCE_CONTRACT["defaultCurrency"]
INCOME_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT["incomeCategories"])
EXPENSE_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT["expenseCategories"])
INVESTMENT_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT["investmentCategories"])
ASSET_TYPES = frozenset(FINANCE_CONTRACT["assetTypes"])
FINANCE_ACCOUNT_TYPES = frozenset(FINANCE_CONTRACT["accountTypes"])
LEDGER_RECORD_AMOUNT_PERIODS = frozenset(FINANCE_CONTRACT["ledgerAmountPeriods"])

_LIMITS = FINANCE_CONTRACT["limits"]
MAX_FINANCE_LINES = _LIMITS["maxFinanceLines"]
MAX_FINANCE_DESCRIPTION = _LIMITS["maxFinanceDescription"]
MAX_SOURCE_ASSET_KEYS_PER_LINE = _LIMITS["maxSourceAssetKeysPerLine"]
MAX_SOURCE_ASSET_KEY_LEN = _LIMITS["maxSourceAssetKeyLen"]
MAX_INVESTMENT_PROVIDER_LEN = _LIMITS["maxInvestmentProviderLen"]
MAX_INVESTMENT_TICKER_LEN = _LIMITS["maxInvestmentTickerLen"]
MAX_INVESTMENT_CRYPTO_CURRENCY_LEN = _LIMITS["maxInvestmentCryptoCurrencyLen"]
MAX_LEDGER_RECORDS = _LIMITS["maxLedgerRecords"]
MAX_PENSION_DESCRIPTION_LEN = _LIMITS["maxPensionDescriptionLen"]
MAX_ACCOUNT_DESCRIPTION_LEN = _LIMITS["maxAccountDescriptionLen"]

DEFAULT_EXPENSE_INCOME_ALLOCATION_PERCENTAGES: dict[str, float] = {
    "taxOnIncomePercent": FINANCE_CONTRACT["defaultExpenseIncomeAllocationPercents"]["taxOnIncomePercent"],
    "investmentOnIncomePercent": FINANCE_CONTRACT["defaultExpenseIncomeAllocationPercents"]["investmentOnIncomePercent"],
    "savingOnIncomePercent": FINANCE_CONTRACT["defaultExpenseIncomeAllocationPercents"]["savingOnIncomePercent"],
}

OPENROUTER_TIMEOUT_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT["openRouterTimeoutSeconds"])
PARSE_JOB_STALE_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT["parseJobStaleSeconds"])
PARSE_JOB_STUCK_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT["parseJobStuckSeconds"])
PARSE_JOB_TTL_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT["parseJobTtlSeconds"])
ADMIN_WEB_HOSTNAME = ADMIN_DOMAINS_CONTRACT["adminWebHostname"]
