#!/usr/bin/env python3
"""Generate contract artifacts from contracts/*.json."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
LAMBDA_CONTRACTS = ROOT / "backend" / "lambda" / "admin" / "contracts"
PY_OUT = ROOT / "backend" / "lambda" / "admin" / "contract_constants.py"
TS_OUT = ROOT / "apps" / "admin_web" / "src" / "lib" / "contracts" / "generated.ts"
CDK_OUT = ROOT / "backend" / "infrastructure" / "lib" / "shared-contracts.ts"


def load(name: str) -> dict:
    with (CONTRACTS / name).open(encoding="utf-8") as f:
        return json.load(f)


def py_repr(value: object) -> str:
    return repr(value)


def write_python(finance: dict, timeouts: dict, domains: dict) -> None:
    LAMBDA_CONTRACTS.mkdir(parents=True, exist_ok=True)
    for name in ("finance.json", "parse-timeouts.json", "admin-domains.json"):
        shutil.copy2(CONTRACTS / name, LAMBDA_CONTRACTS / name)

    lines = [
        '"""Generated by scripts/sync-contracts.py — do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "import json",
        "",
        "_CONTRACTS_DIR = Path(__file__).resolve().parent / \"contracts\"",
        "",
        "def _load(name: str) -> dict:",
        "    with (_CONTRACTS_DIR / name).open(encoding=\"utf-8\") as f:",
        "        return json.load(f)",
        "",
        "FINANCE_CONTRACT = _load(\"finance.json\")",
        "PARSE_TIMEOUTS_CONTRACT = _load(\"parse-timeouts.json\")",
        "ADMIN_DOMAINS_CONTRACT = _load(\"admin-domains.json\")",
        "",
        "FINANCE_HOUSE_KEYS = frozenset(FINANCE_CONTRACT[\"houses\"])",
        "FINANCE_LINE_TYPES = frozenset(FINANCE_CONTRACT[\"lineTypes\"])",
        "SUPPORTED_FINANCE_CURRENCIES = frozenset(FINANCE_CONTRACT[\"currencies\"])",
        "DEFAULT_FINANCE_CURRENCY = FINANCE_CONTRACT[\"defaultCurrency\"]",
        "INCOME_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT[\"incomeCategories\"])",
        "EXPENSE_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT[\"expenseCategories\"])",
        "INVESTMENT_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT[\"investmentCategories\"])",
        "ASSET_TYPES = frozenset(FINANCE_CONTRACT[\"assetTypes\"])",
        "FINANCE_ACCOUNT_TYPES = frozenset(FINANCE_CONTRACT[\"accountTypes\"])",
        "LEDGER_RECORD_AMOUNT_PERIODS = frozenset(FINANCE_CONTRACT[\"ledgerAmountPeriods\"])",
        "",
        "_LIMITS = FINANCE_CONTRACT[\"limits\"]",
        "MAX_FINANCE_LINES = _LIMITS[\"maxFinanceLines\"]",
        "MAX_FINANCE_DESCRIPTION = _LIMITS[\"maxFinanceDescription\"]",
        "MAX_SOURCE_ASSET_KEYS_PER_LINE = _LIMITS[\"maxSourceAssetKeysPerLine\"]",
        "MAX_SOURCE_ASSET_KEY_LEN = _LIMITS[\"maxSourceAssetKeyLen\"]",
        "MAX_INVESTMENT_PROVIDER_LEN = _LIMITS[\"maxInvestmentProviderLen\"]",
        "MAX_INVESTMENT_TICKER_LEN = _LIMITS[\"maxInvestmentTickerLen\"]",
        "MAX_INVESTMENT_CRYPTO_CURRENCY_LEN = _LIMITS[\"maxInvestmentCryptoCurrencyLen\"]",
        "MAX_LEDGER_RECORDS = _LIMITS[\"maxLedgerRecords\"]",
        "MAX_PENSION_DESCRIPTION_LEN = _LIMITS[\"maxPensionDescriptionLen\"]",
        "MAX_ACCOUNT_DESCRIPTION_LEN = _LIMITS[\"maxAccountDescriptionLen\"]",
        "",
        "DEFAULT_EXPENSE_INCOME_ALLOCATION_PERCENTAGES: dict[str, float] = {",
        "    \"taxOnIncomePercent\": FINANCE_CONTRACT[\"defaultExpenseIncomeAllocationPercents\"][\"taxOnIncomePercent\"],",
        "    \"investmentOnIncomePercent\": FINANCE_CONTRACT[\"defaultExpenseIncomeAllocationPercents\"][\"investmentOnIncomePercent\"],",
        "    \"savingOnIncomePercent\": FINANCE_CONTRACT[\"defaultExpenseIncomeAllocationPercents\"][\"savingOnIncomePercent\"],",
        "}",
        "",
        "OPENROUTER_TIMEOUT_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT[\"openRouterTimeoutSeconds\"])",
        "PARSE_JOB_STALE_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT[\"parseJobStaleSeconds\"])",
        "PARSE_JOB_STUCK_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT[\"parseJobStuckSeconds\"])",
        "PARSE_JOB_TTL_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT[\"parseJobTtlSeconds\"])",
        "ADMIN_WEB_HOSTNAME = ADMIN_DOMAINS_CONTRACT[\"adminWebHostname\"]",
        "",
    ]
    PY_OUT.write_text("\n".join(lines), encoding="utf-8")


def write_typescript(finance: dict, timeouts: dict, domains: dict) -> None:
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    currencies = finance["currencies"]
    limits = finance["limits"]
    body = f"""/** Generated by scripts/sync-contracts.py — do not edit by hand. */

export const SUPPORTED_CURRENCIES = {json.dumps(currencies)} as const;
export type CurrencyCode = (typeof SUPPORTED_CURRENCIES)[number];
export const GLOBAL_DEFAULT_CURRENCY: CurrencyCode = {json.dumps(finance["defaultCurrency"])};

export const FINANCE_HOUSE_KEYS = {json.dumps(finance["houses"])} as const;
export type HouseKey = (typeof FINANCE_HOUSE_KEYS)[number];

export const INCOME_CATEGORIES = {json.dumps(finance["incomeCategories"])} as const;
export const EXPENSE_CATEGORIES = {json.dumps(finance["expenseCategories"])} as const;
export const INVESTMENT_CATEGORIES = {json.dumps(finance["investmentCategories"])} as const;
export const ASSET_TYPES = {json.dumps(finance["assetTypes"])} as const;
export const FINANCE_ACCOUNT_TYPES = {json.dumps(finance["accountTypes"])} as const;

export const MAX_FINANCE_LINES = {limits["maxFinanceLines"]};
export const MAX_FINANCE_DESCRIPTION = {limits["maxFinanceDescription"]};
export const MAX_SOURCE_ASSET_KEYS_PER_LINE = {limits["maxSourceAssetKeysPerLine"]};
export const MAX_SOURCE_ASSET_KEY_LEN = {limits["maxSourceAssetKeyLen"]};
export const MAX_INVESTMENT_PROVIDER_LEN = {limits["maxInvestmentProviderLen"]};
export const MAX_INVESTMENT_TICKER_LEN = {limits["maxInvestmentTickerLen"]};
export const MAX_INVESTMENT_CRYPTO_CURRENCY_LEN = {limits["maxInvestmentCryptoCurrencyLen"]};
export const MAX_LEDGER_RECORDS = {limits["maxLedgerRecords"]};
export const MAX_PENSION_DESCRIPTION_LEN = {limits["maxPensionDescriptionLen"]};
export const MAX_ACCOUNT_DESCRIPTION_LEN = {limits["maxAccountDescriptionLen"]};

export const PARSE_POLL_DEADLINE_MS = {timeouts["parsePollDeadlineMs"]}
export const PARSE_POLL_INITIAL_WAIT_MS = {timeouts["parsePollInitialWaitMs"]};
export const PARSE_POLL_BACKOFF_CAP_MS = {timeouts["parsePollBackoffCapMs"]};

export const ADMIN_WEB_HOSTNAME = {json.dumps(domains["adminWebHostname"])};
"""
    TS_OUT.write_text(body, encoding="utf-8")


def write_cdk(timeouts: dict, domains: dict) -> None:
    body = f"""/** Generated by scripts/sync-contracts.py — do not edit by hand. */

export const ADMIN_WEB_HOSTNAME = {json.dumps(domains["adminWebHostname"])} as const;

export const PARSE_TIMEOUTS = {{
  lambdaTimeoutSeconds: {timeouts["lambdaTimeoutSeconds"]},
  openRouterTimeoutSeconds: {timeouts["openRouterTimeoutSeconds"]},
  parseJobStaleSeconds: {timeouts["parseJobStaleSeconds"]},
  parseJobStuckSeconds: {timeouts["parseJobStuckSeconds"]},
  parseJobTtlSeconds: {timeouts["parseJobTtlSeconds"]},
  parsePollDeadlineMs: {timeouts["parsePollDeadlineMs"]},
}} as const;
"""
    CDK_OUT.write_text(body, encoding="utf-8")


def main() -> None:
    finance = load("finance.json")
    timeouts = load("parse-timeouts.json")
    domains = load("admin-domains.json")
    write_python(finance, timeouts, domains)
    write_typescript(finance, timeouts, domains)
    write_cdk(timeouts, domains)
    print("Synced contract artifacts.")


if __name__ == "__main__":
    main()
